- hosts: '{{ host }}'
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@18.136.160.61"'
   ansible_user: centos
  roles:
   - ssh-key
  tags:
   - manage_user
  vars_files:
    - "group_vars/aws_credentials.yml"
    - "group_vars/vars.yml"
    - "group_vars/users.yml"
    - "group_vars/cidr_blocks.yml"
    - "configs/ci_server.yml"
    - "configs/proxy.yml"
    - "configs/instances.yml"
    - "configs/docker_node.yml"
    - "configs/docker_swarm.yml"