- hosts: "{{ host | default('tag_Name_proxy') }}"
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@18.136.160.61"'
   ansible_user: centos
  roles:
    - haproxy
  vars_files:
    - "group_vars/aws_credentials.yml"
  tags:
    - update_proxy