- include: admin_groups.yml
  with_items: "{{admins}}"
  when: item.admin is defined

- include: developer_groups.yml
  with_items: "{{developers}}"
  when: (item.admin is not defined and ec2_tag_env == "public") or (item.admin is not defined and ec2_tag_env == "showcase")
