build_server_spec:
   Tags: {"role": "build-server", "server_type": "private", "env": "dev" }
   StartIndex: 1
   ExactCount: 1
   InstanceType: t2.xlarge
   SecurityGroups:
     - "{{ SecurityGroupIds.private_sg }}"
   AmiId: "ami-004b761553a4eca7c"
   SubnetId: "{{ SubnetIds.private }}"
   AssignPublicIp: no
   InstanceVolumes:
     - VolumeSpecifications:
         - volume_size: 250
           volume_type: gp2
           device_name: /dev/sda1
           delete_on_termination: no
           FilesystemSpecifications:
             volume_label: "root"
           mountpoint: /