docker_swarm_env_spec:
   Tags: {"role": "docker-swarm", "server_type": "private", "env": "dev" }
   StartIndex: 1
   ExactCount: 1
   InstanceType: t2.xlarge
   SecurityGroups:
     - "{{ SecurityGroupIds.private_sg }}"
   AmiId: "{{ available_amis.docker_host_ami }}"
   SubnetId: "{{ SubnetIds.private }}"
   AssignPublicIp: no
   InstanceVolumes:
     - VolumeSpecifications:
         - volume_size: 150
           volume_type: gp2
           device_name: /dev/sda1
           delete_on_termination: yes
           FilesystemSpecifications:
             volume_label: "root"
           mountpoint: /