proxy_spec:
   Tags: {"role": "proxy", "type": "private-public", "env": "public"}
   StartIndex: 1
   ExactCount: 1
   InstanceType: t2.medium
   SecurityGroups:
     - "{{ SecurityGroupIds.public_sg }}"
   AmiId: "{{ available_amis.hardened_ami }}"
   SubnetId: "{{ SubnetIds.public }}"
   public_ip: "18.136.160.61"
   InstanceVolumes:
     - VolumeSpecifications:
         - volume_size: 40
           volume_type: gp2
           device_name: /dev/sda1
           delete_on_termination: yes
           FilesystemSpecifications:
             volume_label: "root"
           mountpoint: /