- name:               Create Public Subnet
  ec2_vpc_subnet:
    state:            present
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ cidr_blocks.public_subnet }}"
    az:               "{{ aws_region }}a"
    region:           "{{ aws_region }}"
    map_public: no
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    resource_tags:
      Name:           "public"
  register: public_subnet

- name:               Create Private Subnet
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ cidr_blocks.private_subnet }}"
    az:               "{{ aws_region }}a"
    region:           "{{ aws_region }}"
    map_public: no
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    resource_tags:
      Name:           "private"
  register: private_subnet

- name:               Set Subnet ID in variable
  set_fact:
    public_subnet_id: "{{ public_subnet.subnet.id }}"
    private_subnet_id: "{{ private_subnet.subnet.id }}"